# Generated by Django 5.2.4 on 2025-09-28 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='script',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.script'),
        ),
    ]
